# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e962c90bf48c4194c2a8ea4ba0123568f1c4cc25bb389a7969f5941dd50aa1798abfe7b582c40e195b5c7e01d3e61036fd909d5edbedf7b6f59367f13c535d3

test:
  secret_key_base: 79edcc3a635e0cdd0de480bc02812431b1f90aacba33cd127c7637e8e82da0cfa4453762730e9565b493c21804e93687e1cbd73eb65214838971860ff970a8fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
